"""initial migration

Revision ID: 2b65a7b5de2d
Revises: 
Create Date: 2021-02-26 17:04:02.154730

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b65a7b5de2d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sys_menu',
    sa.Column('id', sa.String(length=32), nullable=False, comment='主键'),
    sa.Column('name', sa.String(length=50), nullable=False, comment='菜单/按钮 名称'),
    sa.Column('parent_id', sa.String(length=32), nullable=True, comment='父菜单id'),
    sa.Column('order_num', sa.Integer(), autoincrement=True, nullable=False, comment='显示顺序'),
    sa.Column('path', sa.String(length=256), nullable=False, comment='对应路由地址'),
    sa.Column('menu_type', sa.String(length=1), nullable=False, comment='类型 (M目录 C菜单 F按钮)'),
    sa.Column('visible', sa.Boolean(), nullable=False, comment='是否显示'),
    sa.Column('status', sa.SmallInteger(), nullable=True, comment='菜单状态（0正常 1停用）'),
    sa.Column('perm', sa.String(length=100), nullable=False, comment='对应的权限名'),
    sa.Column('icon', sa.String(length=256), nullable=False, comment='图标'),
    sa.ForeignKeyConstraint(['parent_id'], ['sys_menu.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sys_menu_id'), 'sys_menu', ['id'], unique=False)
    op.create_table('sys_role',
    sa.Column('id', sa.String(length=32), nullable=False, comment='主键'),
    sa.Column('name', sa.String(length=50), nullable=False, comment='角色名称'),
    sa.Column('key', sa.String(length=50), nullable=False, comment='角色权限字符串'),
    sa.Column('status', sa.SmallInteger(), nullable=True, comment='角色状态，0正常，1停用'),
    sa.Column('del_flag', sa.Boolean(), nullable=True, comment='删除标志（0:存在 1:删除）'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sys_role_id'), 'sys_role', ['id'], unique=False)
    op.create_table('sys_user',
    sa.Column('id', sa.String(length=32), nullable=False, comment='用户表主键'),
    sa.Column('username', sa.String(length=50), nullable=False, comment='用户名'),
    sa.Column('nickname', sa.String(length=50), nullable=True, comment='昵称'),
    sa.Column('email', sa.String(length=120), nullable=False, comment='邮箱'),
    sa.Column('mobile', sa.String(length=11), nullable=True, comment='手机号'),
    sa.Column('gender', sa.SmallInteger(), nullable=True, comment='性别， 0：男， 1：女'),
    sa.Column('avatar', sa.String(length=150), nullable=True, comment='头像URI'),
    sa.Column('password', sa.String(length=64), nullable=True, comment='密码'),
    sa.Column('status', sa.SmallInteger(), nullable=True, comment='用户状态，0正常 1禁用或停用'),
    sa.Column('is_super', sa.Boolean(), nullable=False, comment='是否为超级管理员'),
    sa.Column('remark', sa.String(length=50), nullable=True, comment='备注'),
    sa.Column('del_flag', sa.Boolean(), nullable=True, comment='是否删除,0：未删除， 1：已删除'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sys_user_email'), 'sys_user', ['email'], unique=True)
    op.create_index(op.f('ix_sys_user_id'), 'sys_user', ['id'], unique=False)
    op.create_table('sys_role_menu',
    sa.Column('role_id', sa.String(length=32), nullable=False),
    sa.Column('menu_id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['menu_id'], ['sys_menu.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['sys_role.id'], ),
    sa.PrimaryKeyConstraint('role_id', 'menu_id')
    )
    op.create_table('sys_user_role',
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('role_id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['sys_role.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['sys_user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'role_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sys_user_role')
    op.drop_table('sys_role_menu')
    op.drop_index(op.f('ix_sys_user_id'), table_name='sys_user')
    op.drop_index(op.f('ix_sys_user_email'), table_name='sys_user')
    op.drop_table('sys_user')
    op.drop_index(op.f('ix_sys_role_id'), table_name='sys_role')
    op.drop_table('sys_role')
    op.drop_index(op.f('ix_sys_menu_id'), table_name='sys_menu')
    op.drop_table('sys_menu')
    # ### end Alembic commands ###
