"""not null

Revision ID: 30f0065092b2
Revises: 2b65a7b5de2d
Create Date: 2021-03-02 18:03:43.554484

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30f0065092b2'
down_revision = '2b65a7b5de2d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sys_menu', sa.Column('del_flag', sa.Boolean(), nullable=False, comment='删除标志（0:存在 1:删除）'))
    op.alter_column('sys_menu', 'status',
               existing_type=sa.SMALLINT(),
               nullable=False,
               existing_comment='菜单状态（0正常 1停用）')
    op.alter_column('sys_role', 'del_flag',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_comment='删除标志（0:存在 1:删除）')
    op.alter_column('sys_role', 'key',
               existing_type=sa.VARCHAR(length=50),
               comment='角色编码',
               existing_comment='角色权限字符串',
               existing_nullable=False)
    op.alter_column('sys_role', 'status',
               existing_type=sa.SMALLINT(),
               nullable=False,
               existing_comment='角色状态，0正常，1停用')
    op.create_unique_constraint(None, 'sys_role', ['key'])
    op.alter_column('sys_user', 'avatar',
               existing_type=sa.VARCHAR(length=150),
               nullable=False,
               existing_comment='头像URI')
    op.alter_column('sys_user', 'del_flag',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_comment='是否删除,0：未删除， 1：已删除')
    op.alter_column('sys_user', 'gender',
               existing_type=sa.SMALLINT(),
               nullable=False,
               existing_comment='性别， 0：男， 1：女')
    op.alter_column('sys_user', 'mobile',
               existing_type=sa.VARCHAR(length=11),
               nullable=False,
               existing_comment='手机号')
    op.alter_column('sys_user', 'nickname',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_comment='昵称')
    op.alter_column('sys_user', 'password',
               existing_type=sa.VARCHAR(length=64),
               nullable=False,
               existing_comment='密码')
    op.alter_column('sys_user', 'remark',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_comment='备注')
    op.alter_column('sys_user', 'status',
               existing_type=sa.SMALLINT(),
               nullable=False,
               existing_comment='用户状态，0正常 1禁用或停用')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sys_user', 'status',
               existing_type=sa.SMALLINT(),
               nullable=True,
               existing_comment='用户状态，0正常 1禁用或停用')
    op.alter_column('sys_user', 'remark',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_comment='备注')
    op.alter_column('sys_user', 'password',
               existing_type=sa.VARCHAR(length=64),
               nullable=True,
               existing_comment='密码')
    op.alter_column('sys_user', 'nickname',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_comment='昵称')
    op.alter_column('sys_user', 'mobile',
               existing_type=sa.VARCHAR(length=11),
               nullable=True,
               existing_comment='手机号')
    op.alter_column('sys_user', 'gender',
               existing_type=sa.SMALLINT(),
               nullable=True,
               existing_comment='性别， 0：男， 1：女')
    op.alter_column('sys_user', 'del_flag',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_comment='是否删除,0：未删除， 1：已删除')
    op.alter_column('sys_user', 'avatar',
               existing_type=sa.VARCHAR(length=150),
               nullable=True,
               existing_comment='头像URI')
    op.drop_constraint(None, 'sys_role', type_='unique')
    op.alter_column('sys_role', 'status',
               existing_type=sa.SMALLINT(),
               nullable=True,
               existing_comment='角色状态，0正常，1停用')
    op.alter_column('sys_role', 'key',
               existing_type=sa.VARCHAR(length=50),
               comment='角色权限字符串',
               existing_comment='角色编码',
               existing_nullable=False)
    op.alter_column('sys_role', 'del_flag',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_comment='删除标志（0:存在 1:删除）')
    op.alter_column('sys_menu', 'status',
               existing_type=sa.SMALLINT(),
               nullable=True,
               existing_comment='菜单状态（0正常 1停用）')
    op.drop_column('sys_menu', 'del_flag')
    # ### end Alembic commands ###
